server:
  port: 8080
  servlet:
    context-path: /user

spring:
  profiles:
    active: local
  application:
    name: user
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: false
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    hibernate:
      use-new-id-generator-mappings: false

springdoc:
  swagger-ui:
    path: /swagger
    operations-sorter: method
    tags-sorter: method